[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"


[build.environment]
NODE_OPTIONS = "--max-old-space-size=4096"
NEXT_TELEMETRY_DISABLED = "1"
SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL"
# Uncomment the line below to skip Netlify Forms validation if needed
# NETLIFY_NEXT_VERIFY_FORMS = "false"

[functions]
node_bundler = "esbuild"
external_node_modules = [
    "@supabase/ssr",
    "@supabase/supabase-js",
    "next",
    "react",
    "react-dom",
    "@netlify/functions",
    "mailgun.js",
    "form-data",
    "imap-simple",
]

# Explicitly exclude heavy directories from all function bundles
[functions."*"]
excluded_files = [
    "emails/**",
    "emails_backup/**",
    "src/**",
    ".next/**",
    "public/**",
    "node_modules/**",
    "*.md",
    "*.json",
]

[functions.send-scheduled-report]
node_bundler = "esbuild"
external_node_modules = [
    "@supabase/ssr",
    "@supabase/supabase-js",
    "next",
    "react",
    "react-dom",
    "@netlify/functions",
    "mailgun.js",
    "form-data",
    "imap-simple",
]
excluded_files = [
    "emails/**",
    "emails_backup/**",
    "src/**",
    ".next/**",
    "public/**",
    "node_modules/**",
    "*.md",
    "*.json",
]
