[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[build.environment]
NEXT_TELEMETRY_DISABLED = "1"

# Form processing
[[redirects]]
from = "/contact"
to = "/contact/index.html"
status = 200

# API routes
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/___netlify-handler"
status = 200

# Catch-all for Next.js
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
