[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[build.environment]
NEXT_TELEMETRY_DISABLED = "1"
SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@supabase/ssr", "@supabase/supabase-js", "next"]
