[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "@netlify/plugin-emails"

[build.environment]
NEXT_TELEMETRY_DISABLED = "1"
SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL"

[functions]
node_bundler = "esbuild"
external_node_modules = [
    "@supabase/ssr",
    "@supabase/supabase-js",
    "next",
    "react",
    "react-dom",
    "@netlify/functions",
]

# Explicitly exclude emails directory from all function bundles
[functions."*"]
excluded_files = ["emails/**"]

[functions.send-scheduled-report]
node_bundler = "esbuild"
external_node_modules = [
    "@supabase/ssr",
    "@supabase/supabase-js",
    "next",
    "react",
    "react-dom",
    "@netlify/functions",
]
excluded_files = ["emails/**"]
